dist: trusty # 14.04
sudo: required

language: cpp

#compiler:
#  - clang
#  - gcc

env:
  - QMAKESPEC=linux-clang
  - QMAKESPEC=linux-g++

before_install:
  - sudo apt-get update
  - sudo apt-get install -y qt5-default
  - sudo apt-get install -y libglu1-mesa-dev
  - sudo apt-get install -y xorg-dev
  - sudo apt-get install -y libopenal-dev
  - sudo apt-get install -y libwavpack-dev

script:
  - cd BUILD_QTCREATOR
  - qmake -qt=qt5
  - make
  - cd output/release
  - ./autotest1
  - ./autotest2
  - ./autotest3
  - dd if=/dev/urandom of=./test.bin count=50 ibs=1M # тест на чтение 50МиБ файла
  - ./filecopy ./test.bin ./copy.bin
  - cmp ./test.bin ./copy.bin
  - dd if=/dev/urandom of=./test.bin count=1 ibs=1M # тест на чтение 1МиБ файла
  - ./filecopy ./test.bin ./copy.bin
  - cmp ./test.bin ./copy.bin
#  - dd if=/dev/urandom of=./test.bin count=5120 ibs=1M # тест на чтение 5ГиБ файла
#  - ./filecopy ./test.bin ./copy.bin
#  - cmp ./test.bin ./copy.bin
  - dd if=/dev/urandom of=./тест.бин count=1 ibs=1M # тест юникод имён
  - ./filecopy ./тест.бин ./копи.бин
  - cmp ./тест.бин ./копи.бин

branches:
  only:
  - master
